### ISSUE TITLE
extraction of personal data is problematic

### ISSUE THREAD

**Issue by thomasbtf** [thomasbtf/document-anonymization#28]
```
Traceback (most recent call last):
  File "/local/data/dev/thomas/document-anonymization/.snakemake/scripts/tmpn0w1zv0b.extract-personal-data.py", line 128, in <module>
    var_data = variate_personal_data(personal_data[0], personal_data[1])
  File "/local/data/dev/thomas/document-anonymization/.snakemake/scripts/tmpn0w1zv0b.extract-personal-data.py", line 63, in variate_personal_data
    for i, perm in enumerate(all_name_perms):
TypeError: 'NoneType' object is not iterable
```

**Comment by thomasbtf** [comment]
closed in #36
